### PR TITLE
Let's not run the processes as root

### PR DESCRIPTION
**Pull request by trick77**
This change drops privileges before starting the node.

```
ps -elf
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S bc           1     0 30  80   0 - 795974 ep_pol 22:09 ?       00:00:06 node
4 S bc          19     1  4  80   0 - 259146 ep_pol 22:09 ?       00:00:00 bc-ro
4 S bc          24     1  2  80   0 - 254611 ep_pol 22:09 ?       00:00:00 bc-ro
4 S bc          25     1  4  80   0 - 330872 ep_pol 22:09 ?       00:00:00 bc-ro
4 S bc          31     1  3  80   0 - 319931 ep_pol 22:09 ?       00:00:00 bc-ro
4 S bc          41     1  3  80   0 - 322173 ep_pol 22:09 ?       00:00:00 bc-ro
4 S bc         150     0  0  80   0 -  5065 wait   22:09 pts/0    00:00:00 bash
0 R bc         196   150  0  80   0 -  4376 -      22:09 pts/0    00:00:00 ps -e
```

### CODE REVIEW

**Comment by korczis** [comment]
@trick77 Thanks for contribution.

BTW: Can you update (rebase) your PR, please?

**Comment by korczis** [comment]
@trick77 Can you rebase this, please?

**Comment by trick77** [comment]
I asked you if PR should go against master and you said yes. So at the time of the PR, this was based properly against master. I'm closing it. I don't see a reason for "forever" in the Docker context as you could just use a restart-policy.

**Comment by trick77** [comment]
@korczis here's how I would set up a Docker project for bcnode:
https://github.com/trick77/docker-blockcollider

**Pull request closed without merging**
